services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: "always"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ../frontend/.env
    ports:
      - "3000:3000"
    restart: "always"
    volumes:
      - ../frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ../backend/.env
    ports:
      - "3001:3001"
    restart: "always"
    volumes:
      - ../backend:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


  hardhat-node:
    build:
      context: ../contracts
      dockerfile: Dockerfile
    container_name: contracts_node
    ports:
      - "8545:8545"
    volumes:
      - ../contracts:/app
      - /app/node_modules
    command: npx hardhat node --hostname 0.0.0.0

  hardhat-deploy:
    build:
      context: ../contracts
      dockerfile: Dockerfile
    container_name: contracts_deploy
    depends_on:
      - hardhat-node
    volumes:
      - ../contracts:/app
      - /app/node_modules
    environment:
      - LOCALHOST_RPC_URL=http://hardhat-node:8545
    command: npx hardhat ignition deploy ignition/modules/Token.ts --network localhost

volumes:
  redis_data:
